= Zertifizierte CAPI-Anbieter
:revdate: 2025-10-14
:page-revdate: {revdate}

== Was bedeutet "Zertifizierte Anbieter"?

Zertifizierte Provider sind CAPI-Provider, die **aktiv** von den CI-Workflows des Turtles-Teams **getestet** werden, um sicherzustellen, dass sie mit der CAPI-Erweiterung für Rancher ordnungsgemäß funktionieren. Da es sich bei den meisten CAPI-Providern jedoch um Upstream-Projekte handelt, die von der offenen Kubernetes-Community gepflegt werden, **können wir nicht garantieren,** dass keine Probleme auftreten, wenn neue Provider-Versionen veröffentlicht werden.

== Liste der zertifizierten Anbieter

[NOTE]
====
Diese Liste wird ständig weiterentwickelt, um der laufenden Entwicklung des Projekts Rechnung zu tragen.
====


Dies ist eine Liste der offiziell von Turtles zertifizierten CAPI-Anbieter. Diese Anbieter werden von unserer Testsuite abgedeckt und wir stellen aktiv sicher, dass sie mit der CAPI-Erweiterung für Rancher ordnungsgemäß funktionieren.

|===
| Platform | Code Name | Anbieter Typ | Dokumente

| *RKE2*
| CAPRKE2
| Bootstrap/Steuerebene
| https://rancher.github.io/cluster-api-provider-rke2[CAPRKE2-Buch]

| *Kubeadm*
| Kubeadm
| Bootstrap/Steuerebene
| https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap[CABPK-Dokumente]

| *AWS*
| CAPA
| Infrastruktur
| https://cluster-api-aws.sigs.k8s.io[CAPA-Buch]

| *Docker**
| CAPD
| Infrastruktur
| https://cluster-api.sigs.k8s.io[CAPI-Buch]

| *vSphere*
| CAPV
| Infrastruktur
| https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/getting_started.md[CAPV-Dokumente]

| *Azure*
| CAPZ
| Infrastruktur
| https://capz.sigs.k8s.io/[CAPZ-Buch]

| *GCP* (nur von GKE verwaltete Cluster)
| CAPG
| Infrastruktur
| https://cluster-api-gcp.sigs.k8s.io/[CAPG-Buch]

| *Addon-Anbieter Flotte*
| CAAPF
| Zusatzartikel
| https://rancher.github.io/cluster-api-addon-provider-fleet/[CAAPF-Buch]
|===

*Empfohlen nur für Entwicklungszwecke.

== Liste der Anbieter im experimentellen Modus

Dies ist eine Liste von Anbietern, die sich in einem fortgeschrittenen Entwicklungsstadium befinden und demnächst zertifiziert werden.

|===
| Platform | Code Name | Anbieter Typ | Dokumente
|===

== ClusterClass-Support für zertifizierte Anbieter

Nachfolgend finden Sie eine Support-Matrix für jeden zertifizierten Anbieter und dessen Unterstützung für die Cluster-Topologie-Funktion:

[tabs]
======
CAPZ::
+
--
- **Volle Unterstützung** von `+ClusterClass+`: Sowohl verwaltete (AKS) als auch nicht verwaltete (virtuelle Maschinen) Cluster können über die Topologie bereitgestellt werden.
--

CAPA::
+
--
- **Vollständige Unterstützung** von `+ClusterClass+`: Sowohl verwaltete (EKS) als auch nicht verwaltete (EC2-basierte) Cluster können über die Topologie bereitgestellt werden.
--

CAPG::
+
--
- **Vollständige Unterstützung** von `+ClusterClass+`: Sowohl verwaltete (GKE) als auch nicht verwaltete (virtuelle Maschinen) Cluster können über die Topologie bereitgestellt werden.
--

CAPRKE2::
+
--
- **Volle Unterstützung** von `+ClusterClass+`.
--

CABPK::
+
--
- **Volle Unterstützung** von `+ClusterClass+`.
--

CAPV::
+
--
- **Volle Unterstützung** von `+ClusterClass+`.
--

CAPD::
+
--
- **Volle Unterstützung** von `+ClusterClass+`.
--
======
