include::partial$variables.adoc[]
= Sigstore-Host-Fähigkeiten
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Erfahren Sie, wie Sie Sigstore-Host-Funktionen mit CEL-Richtlinien in Kubewarden implementieren, um Container-Images zu verifizieren und eine sichere Zugangskontrolle durchzusetzen.
:doc-persona: ["kubewarden-policy-developer", "kubewarden-operator"]
:doc-topic: ["kubewarden", "writing-policies", "cel", "sigstore", "signature", "verification"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "writing policies", "sigstore", "signature", "verification"]
:sidebar_label: Sigstore-Host-Fähigkeiten
:current-version: {page-origin-branch}

Als Beispiel für eine andere Nutzung der Host-Fähigkeiten auf`+cel-policy+` von kubewarden wollen wir eine Richtlinie erstellen, die alle Container-Images in einem Pod durch Überprüfung ihrer Sigstore-Keyless-Signaturen verifiziert.

== Beispiel: Sigstore-Verifizierungspolitik

Diese Richtlinie überprüft alle Container-Images im Pod Sigstore und stellt sicher, dass die Images signiert und vertrauenswürdig sind.

In diesem Fall wird in GitHub Actions nach einer Sigstore Keyless Signatur gesucht. Diese Art von schlüssellosen Signaturen sind bei der Erstellung der kryptografischen Zertifikate an den OIDC-Aussteller von GitHub gebunden, sodass wir nur die GitHub-Organisation kennen müssen, unter der das Container-Image veröffentlicht wird. Mehr über die Host-Fähigkeiten von Sigstore können Siexref:reference/spec/host-capabilities/02-signature-verifier-policies.adoc[hier] lesen.

Um dies in CEL zu erreichen, verwenden wir die https://github.com/kubewarden/cel-policy?tab=readme-ov-file#host-capabilities[{project-name}'s CEL-Erweiterungsbibliotheken für Host-Fähigkeiten] in der Politik, insbesondere die https://pkg.go.dev/github.com/kubewarden/cel-policy/internal/cel/library#Sigstore[`+githubAction+`Funktion].

Wie immer können wir mit `+kwctl+` beginnen:

[subs="+attributes",console]
----
$ kwctl scaffold manifest -t ClusterAdmissionPolicy \
  registry://ghcr.io/kubewarden/policies/cel-policy:v1.0.0`
----

Diese können wir dann so bearbeiten, dass sie für unsere Containerprüfungsrichtlinie relevant sind:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
----

Kommen wir nun zum CEL-Teil. Wir erhalten eine Liste der Container-Images im aktuellen Pod-Objekt und überprüfen dann, ob sie durch eine Signatur verifiziert sind, die mit der von uns gewählten Organisation (in diesem Fall github.com/opencontainers) übereinstimmt:

[subs="+attributes",yaml]
----
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  name: "cel-sigstore-keyless-verification"
spec:
  module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations: ["CREATE", "UPDATE"]
  settings:
    variables:
      - name: containerImages
        expression: |
          object.spec.containers.map(c, c.image)
      - name: containerImagesNotVerified
        expression: |
          variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted())
    validations:
      - expression: |
          size(variables.containerImagesNotVerified) == 0
        messageExpression: "'These container images are not signed by the kubewarden GitHub organization: ' + variables.containerImagesNotVerified.join(', ')"
----

Aber halt, wir dürfen nicht vergessen, dass InitContainer auch Teil von Pods sein können. Fügen wir also eine weitere Variable und eine Validierung hinzu:

```yaml title="./cel-policy-sigstore.yaml"
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy metadata: name: "cel-sigstore-keyless-verification" spec: module: ghcr.io/kubewarden/policies/cel-policy:v1.0.0 namespaceSelector: matchLabels: kubernetes.io/metadata.name: default rules:- apiGroups: [""] apiVersions: ["v1"] resources: ["pods"] operations: ["CREATE", "UPDATE"] settings: variables: - name: containerImages expression: | object.spec.containers.map(c, c.image) - name: initContainerImages Ausdruck: | has(object.spec.initContainerImages) ? object.spec.initContainers.map(c, c.image) : [] - name: containerImagesNotVerified Ausdruck: | variables.containerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) - name: initContainerImagesNotVerified Ausdruck: | variables.initContainerImages.filter(image, !kw.sigstore.image(image).githubAction("opencontainers").verify().isTrusted()) validations:- expression: | size(variables.containerImagesNotVerified) == 0 messageExpression: "'Diese Container-Images sind nicht von der kubewarden GitHub Organisation signiert: ' + variables.containerImagesNotVerified.join(', ')" - expression: | size(variables.initContainerImagesNotVerified) == 0 messageExpression: "'Diese init-Container-Images sind nicht von der kubewarden-GitHub-Organisation signiert: ' + variables.initContainerImagesNotVerified.join(', ')"
```

As usual with CEL, we can add several `+validations+` under
`+settings.validations+`, and they are evaluated in parallel, joined with an AND
operation, which is short-circuited.

We can now deploy the policy, and try to deploy a Pod with unsigned images:

```console
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: golanci-lint-example
spec:
  containers:
  - name: nginx
    image: ghcr.io/opencontainers/golangci-lint:v1.52.1
    ports:
    - containerPort: 80
EOF
Error from server: error when creating "STDIN":
  admission webhook "clusterwide-cel-sigstore-keyless-verification.kubewarden.admission" denied the request:
  failed to verify image: Callback evaluation failure: no signatures found for image: ghcr.io/opencontainers/golangci-lint:v1.52.1
```
