include::partial$variables.adoc[]
= Validierungslogik schreiben
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Schreiben Sie eine Validierungslogik, um die Gültigkeit eingehender Anfragen zu prüfen, indem Sie Nutzdaten analysieren und Pod-Objekte verifizieren.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["kubewarden", "writing-policies", "rust", "validation-logic"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "policy", "writing", "rust", "validation logic"]
:sidebar_label: Validierungslogik schreiben
:current-version: {page-origin-branch}

Nun ist es an der Zeit, den eigentlichen Validierungscode zu schreiben.
Sie ist in der Datei `+src/lib.rs+` definiert.
In dieser Datei finden Sie eine Funktion namens `+validate+`.

Dies ist die Funktion des Gerüsts:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: ValidationRequest<Settings> = ValidationRequest::new(payload)?; <1>

    info!(LOG_DRAIN, "starting validation");
    if validation_request.request.kind.kind != apicore::Pod::KIND {
        warn!(LOG_DRAIN, "Policy validates Pods only. Accepting resource"; "kind" => &validation_request.request.kind.kind);
        return kubewarden::accept_request();
    }
    // TODO: you can unmarshal any Kubernetes API type you are interested in <2>
    match serde_json::from_value::<apicore::Pod>(validation_request.request.object) {
        Ok(pod) => {
            // TODO: your logic goes here <3>
            if pod.metadata.name == Some("invalid-pod-name".to_string()) {
                let pod_name = pod.metadata.name.unwrap();
                info!(
                    LOG_DRAIN,
                    "rejecting pod";
                    "pod_name" => &pod_name
                );
                kubewarden::reject_request(
                    Some(format!("pod name {} is not accepted", &pod_name)),
                    None,
                    None,
                    None,
                )
            } else {
                info!(LOG_DRAIN, "accepting resource");
                kubewarden::accept_request()
            }
        }
        Err(_) => {
            // TODO: handle as you wish
            // We were forwarded a request we cannot unmarshal or
            // understand, just accept it
            warn!(LOG_DRAIN, "cannot unmarshal resource: this policy does not know how to evaluate this resource; accept it");
            kubewarden::accept_request() <4>
        }
    }
}
----


Gehen Sie durch das Code-Listing:

* In der mit ➀ gekennzeichneten Zeile. Parsen der eingehenden `+payload+` in ein `+ValidationRequest<Setting>+` Objekt.
Dadurch wird die Instanz `+Settings+` in `+ValidationRequest+` automatisch mit den vom Benutzer angegebenen Parametern gefüllt.
* In der mit ➁ gekennzeichneten Zeile. Konvertiert das in die Anfrage eingebettete Kubernetes-Roh-JSON-Objekt in eine Instanz derhttps://arnavion.github.io/k8s-openapi/v0.25.x/k8s_openapi/api/core/v1/struct.Pod.html[Pod-Struktur]
* In der mit ➂ gekennzeichneten Zeile. Die Anfrage hat ein Pod-Objekt, der Code genehmigt nur die Anfragen, bei denen `+metadata.name+` nicht dem fest programmierten Wert entspricht `+invalid-pod-name+`
* In der mit ➃ gekennzeichneten Zeile. Die Anfrage enthält kein Pod-Objekt, daher akzeptiert die Richtlinie die Anfrage.

Wie Sie sehen können, führt der Code bereits eine Validierung durch, die derjenigen ähnelt, die Sie implementieren möchten.
Sie müssen nur den fest kodierten Wert entfernen und die vom Benutzer über die Richtlinieneinstellungen angegebenen Werte verwenden.

Sie können die Funktion `+validate+` in `+src/lib.rs+` durch diese Funktion ersetzen:

[subs="+attributes",rust]
----
fn validate(payload: &[u8]) -> CallResult {
    let validation_request: ValidationRequest<Settings> = ValidationRequest::new(payload)?;

    info!(LOG_DRAIN, "starting validation");
    if validation_request.request.kind.kind != apicore::Pod::KIND {
        warn!(LOG_DRAIN, "Policy validates Pods only. Accepting resource"; "kind" => &validation_request.request.kind.kind);
        return kubewarden::accept_request();
    }

    match serde_json::from_value::<apicore::Pod>(validation_request.request.object) {
        Ok(pod) => {
            let pod_name = pod.metadata.name.unwrap_or_default();
            if validation_request
                .settings
                .invalid_names
                .contains(&pod_name)
            {
                kubewarden::reject_request(
                    Some(format!("pod name {:?} is not accepted", pod_name)),
                    None,
                    None,
                    None,
                )
            } else {
                kubewarden::accept_request()
            }
        }
        Err(_) => {
            // We were forwarded a request we cannot unmarshal or
            // understand, just accept it
            kubewarden::accept_request()
        }
    }
}
----

== Einheitliche Tests

Schließlich können Sie Unit-Tests erstellen, um zu prüfen, ob der Validierungscode wie erwartet funktioniert.

In der Datei `+lib.rs+` sind am Ende der Datei bereits Tests definiert, und wie Sie sehen können, bietet das Rust-SDK von {short-project-name} auch Testhilfen.

Außerdem wird das Scaffold-Projekt bereits mit standardmäßigenhttps://en.wikipedia.org/wiki/Test_fixture#Software[Testfixtures] im Verzeichnis `+test_data+` ausgeliefert. Sie werden diese aufgezeichneten Zulassungsanträge verwenden, um Ihre Einheitstests zu schreiben.

Ändern Sie den Inhalt des Testabschnitts am Ende von `+src/lib.rs+` so, dass er wie folgt aussieht:

[subs="+attributes",rust]
----
#[cfg(test)]
mod tests {
    use super::*;

    use kubewarden_policy_sdk::test::Testcase;
    use std::collections::HashSet;

    #[test]
    fn accept_pod_with_valid_name() -> Result<(), ()> {
        let mut invalid_names = HashSet::new();
        invalid_names.insert(String::from("bad_name1"));
        let settings = Settings { invalid_names };

        let request_file = "test_data/pod_creation.json";
        let tc = Testcase {
            name: String::from("Pod creation with valid name"),
            fixture_file: String::from(request_file),
            expected_validation_result: true,
            settings,
        };

        let res = tc.eval(validate).unwrap();
        assert!(
            res.mutated_object.is_none(),
            "Something mutated with test case: {}",
            tc.name,
        );

        Ok(())
    }

    #[test]
    fn reject_pod_with_invalid_name() -> Result<(), ()> {
        let mut invalid_names = HashSet::new();
        invalid_names.insert(String::from("nginx"));
        let settings = Settings { invalid_names };

        let request_file = "test_data/pod_creation.json";
        let tc = Testcase {
            name: String::from("Pod creation with invalid name"),
            fixture_file: String::from(request_file),
            expected_validation_result: false,
            settings,
        };

        let res = tc.eval(validate).unwrap();
        assert!(
            res.mutated_object.is_none(),
            "Something mutated with test case: {}",
            tc.name,
        );

        Ok(())
    }

    #[test]
    fn accept_request_with_non_pod_resource() -> Result<(), ()> {
        let mut invalid_names = HashSet::new();
        invalid_names.insert(String::from("prod"));
        let settings = Settings { invalid_names };

        let request_file = "test_data/ingress_creation.json";
        let tc = Testcase {
            name: String::from("Ingress creation"),
            fixture_file: String::from(request_file),
            expected_validation_result: true,
            settings,
        };

        let res = tc.eval(validate).unwrap();
        assert!(
            res.mutated_object.is_none(),
            "Something mutated with test case: {}",
            tc.name,
        );

        Ok(())
    }
}
----

Sie haben nun drei Unit-Tests in `+lib.rs+` definiert:

* `+accept_pod_with_valid_name+`akzeptiert einen Pod mit einem gültigen Namen
* `+reject_pod_with_invalid_name+`Pod mit ungültigem Namen wird abgelehnt
* `+accept_request_with_non_pod_resource+`: Anfragen akzeptieren, die kein `+Pod+` als Objekt haben

Sie können die Unit-Tests erneut ausführen:

[subs="+attributes",shell]
----
$ cargo test
   Compiling demo v0.1.0 (/home/flavio/hacking/kubernetes/kubewarden/demo)
    Finished test [unoptimized + debuginfo] target(s) in 3.45s
     Running target/debug/deps/demo-24670dd6a538fd72

running 5 tests
test settings::tests::accept_settings_with_a_list_of_invalid_names ... ok
test settings::tests::reject_settings_without_a_list_of_invalid_names ... ok
test tests::accept_request_with_non_pod_resource ... ok
test tests::accept_pod_with_valid_name ... ok
test tests::reject_pod_with_invalid_name ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
----

Das ist alles, was erforderlich ist, wenn Sie eine einfache Validierungsrichtlinie schreiben müssen.
