= Erforderliche Berechtigungen
:revdate: 2025-07-10
:page-revdate: {revdate}
:description: SUSE Observability Selbstgehostet

== Übersicht

Alle Komponenten von SUSE Observability können ohne zusätzliche Berechtigungen ausgeführt werden. Für eine erfolgreiche Installation von SUSE Observability benötigen Sie jedoch einige zusätzliche Berechtigungen, oder Sie müssen sicherstellen, dass die auf dieser Seite beschriebenen Anforderungen erfüllt sind.

== Dienst-zu-Dienst-Authentifizierung und -Autorisierung

Um die Kommunikation zwischen SUSE Observability-Services zu ermöglichen, verwendet SUSE Observability Kubernetes-Servicekonten. Um deren Gültigkeit und Rollen überprüfen zu können, erstellt die Steuerkarte eine `ClusterRole` und eine `ClusterRoleBinding` Ressource. Das Erstellen dieser clusterweiten Ressourcen ist für Benutzer, die keine Kubernetes/OpenShift-Administratoren sind, oft nicht möglich. In diesem Fall kann die Erstellung deaktiviert werden und stattdessen müssen die Rollen und Rollenbindungen xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_manually_create_cluster_wide_resources[manuell] von Ihrem Cluster-Administrator xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_manually_create_cluster_wide_resources[erstellt] werden.

=== Automatische Erstellung von clusterweiten Ressourcen deaktivieren

Die automatische Erstellung von clusterweiten Ressourcen während der Installation von SUSE Observability kann durch Hinzufügen des folgenden Abschnitts zur Datei `values.yaml`, die zur Installation von SUSE Observability verwendet wird, deaktiviert werden:

[tabs]
====
values.yaml::
+
--

[,yaml]
----
cluster-role:
  enabled: false
----

--
====

[NOTE]
====
Wenn die Erstellung der Cluster-Rolle und der Cluster-Rollen-Bindung deaktiviert wurde, folgen Sie bitte den nachstehenden Anweisungen, um sie manuell zu erstellen, indem Sie die xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_manually_create_cluster_wide_resources[nachstehenden Anweisungen] verwenden.
====


=== Manuelles Erstellen von clusterweiten Ressourcen

Wenn Sie die clusterweiten Ressourcen manuell erstellen müssen, bitten Sie Ihren Kubernetes/OpenShift-Administrator, die 3 unten aufgeführten Ressourcen im Cluster zu erstellen.

[NOTE]
====
Vergewissern Sie sich, dass Sie das richtige Dienstkonto und den richtigen Namespace für die gebundenen `ServiceAccount` für beide `ClusterRoleBinding` Ressourcen angeben. Das Beispiel geht davon aus, dass der Namensraum `suse-observability` verwendet wird und dass `suse-observability` als Freigabe verwendet wird, wenn ein anderer Namensraum verwendet wird, wird der Namensraum in den Beispielen geändert. Auch die referenzierten Dienstkonten müssen in `<release>-suse-observability-api` geändert werden.
====


[tabs]
====
clusterrole-authorization.yaml::
+
--

[,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suse-observability-authorization
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
----

--
====

[tabs]
====
clusterrolebinding-authentication.yaml::
+
--

[,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suse-observability-authentication
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: suse-observability-api
  namespace: suse-observability
----

--
====

[tabs]
====
clusterrolebinding-authorization.yaml::
+
--

[,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suse-observability-authorization
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: suse-observability-authorization
subjects:
- kind: ServiceAccount
  name: suse-observability-api
  namespace: suse-observability
----

--
====

== Pod-Sicherheitsstandards

Wenn in Ihrem Kubernetes-Cluster https://kubernetes.io/docs/concepts/security/pod-security-standards/[die], müssen Sie entsprechende Sicherheitsrichtlinien für den `suse-observability` Namespace konfigurieren. SUSE Observability benötigt den Pod-Sicherheitsstandard, um ordnungsgemäß zu funktionieren.

=== Pod-Sicherheitsstandards konfigurieren

Wenden Sie den grundlegenden Pod-Sicherheitsstandard auf den Namensraum `suse-observability` an:

[,bash]
----
kubectl label ns suse-observability pod-security.kubernetes.io/enforce=baseline --overwrite
kubectl label ns suse-observability pod-security.kubernetes.io/audit=baseline --overwrite
kubectl label ns suse-observability pod-security.kubernetes.io/warn=baseline --overwrite
----

[NOTE]
====
Wenn in Ihrem Cluster Pod-Sicherheitsstandards aktiviert sind, müssen Sie sicherstellen, dass die Elasticsearch-Voraussetzungen vor der Implementierung von SUSE Observability ordnungsgemäß konfiguriert sind.
Da der Baseline Pod Security Standard keine privilegierten Container zulässt, müssen Sie xref:/setup/install-stackstate/kubernetes_openshift/required_permissions.adoc#_elasticsearch[die Anweisungen] zur Konfiguration des erforderlichen `vm.max_map_count` Kernel-Parameters auf Host-Ebene befolgen.
====


== Elasticsearch

SUSE Observability verwendet Elasticsearch zum Speichern seiner Indizes. Es gibt einige zusätzliche Anforderungen an die Knoten, auf denen Elasticsearch läuft.

Da die Linux-Systemeinstellung `vm.max_map_count` in der Regel niedriger ist als für den Start von Elasticsearch erforderlich, wird ein init-Container verwendet, der im privilegierten Modus und als root-Benutzer läuft. Der init-Container ist standardmäßig aktiviert, damit die Systemeinstellung `vm.max_map_count` geändert werden kann.

=== Deaktivieren Sie den privilegierten Elasticsearch-Init-Container

Falls Sie oder Ihre Kubernetes/OpenShift-Administratoren nicht möchten, dass der privilegierte Elasticsearch-Init-Container standardmäßig aktiviert wird, können Sie dieses Verhalten in der Datei `values.yaml` deaktivieren, die zur Installation von SUSE Observability verwendet wird:

[tabs]
====
values.yaml::
+
--

[,yaml]
----
elasticsearch:
  sysctlInitContainer:
    enabled: false
----

--
====

[NOTE]
====
Wenn diese Funktion deaktiviert ist, müssen Sie sicherstellen, dass die Einstellung `vm.max_map_count` von ihrem üblichen Standardwert `65530` auf `262144` geändert wird. Wenn dies nicht geschieht, kann Elasticsearch nicht gestartet werden und seine Pods befinden sich in einer Neustartschleife.
====


Führen Sie den folgenden Befehl aus, um die aktuelle Einstellung `vm.max_map_count` zu überprüfen. Beachten Sie, dass er einen privilegierten Pod ausführt:

[,text]
----
kubectl run -i --tty sysctl-check-max-map-count --privileged=true  --image=busybox --restart=Never --rm=true -- sysctl vm.max_map_count
----

Wenn die aktuelle Einstellung `vm.max_map_count` nicht mindestens `262144` ist, muss sie auf andere Weise erhöht werden, da Elasticsearch sonst nicht gestartet werden kann und seine Pods in einer Neustartschleife stecken. Die Protokolle werden eine Fehlermeldung wie diese enthalten:

[,text]
----
bootstrap checks failed
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
----

=== Erhöhung der Linux-Systemeinstellungen für Elasticsearch

Je nachdem, was Ihre Kubernetes/OpenShift-Administratoren bevorzugen, kann `vm.max_map_count` auf allen Knoten auf einen höheren Standardwert gesetzt werden, indem entweder die Standardkonfiguration des Knotens geändert wird (z. B. über Init-Skripte) oder indem ein DaemonSet dies direkt nach dem Start des Knotens erledigt. Ersteres hängt stark von der Konfiguration Ihres Computers ab, so dass es hier keine allgemeinen Lösungen gibt.

Nachstehend finden Sie ein Beispiel, das als Ausgangspunkt für ein DaemonSet zur Änderung der Einstellung `vm.max_map_count` verwendet werden kann:

[,yaml]
----
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: set-vm-max-map-count
  namespace: kube-system
  labels:
    k8s-app: set-vm-max-map-count
spec:
  selector:
    matchLabels:
      name: set-vm-max-map-count
  template:
    metadata:
      labels:
        name: set-vm-max-map-count
    spec:
      # Make sure the setting always gets changed as soon as possible:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      # Optional node selector (assumes nodes for Elasticsearch are labeled `elasticsearch:yes`
      # nodeSelector:
      #  elasticsearch: yes
      initContainers:
        - name: set-vm-max-map-count
          image: busybox
          securityContext:
            runAsUser: 0
            privileged: true
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      # A pause container is needed to prevent a restart loop of the pods in the daemonset
      # See also this Kubernetes issue https://github.com/kubernetes/kubernetes/issues/36601
      containers:
        - name: pause
          image: busybox
          command: ["sleep", "infinity"]
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
----

Um die Anzahl der Knoten, auf die dies angewandt wird, zu begrenzen, können die Knoten mit einem Etikett versehen werden. NodeSelectors sowohl auf diesem DaemonSet, wie im Beispiel gezeigt, als auch auf dem Elasticsearch-Einsatz können dann so eingestellt werden, dass sie nur auf Knoten mit dem spezifischen Label laufen. Für Elasticsearch kann der Knotenselektor über die Werte angegeben werden:

[,yaml]
----
elasticsearch:
  nodeSelector:
    elasticsearch: yes
  sysctlInitContainer:
    enabled: false
----

== Siehe auch

* xref:/setup/install-stackstate/kubernetes_openshift/kubernetes_install.adoc[SUSE Observability auf Kubernetes installieren]
* xref:/setup/install-stackstate/kubernetes_openshift/openshift_install.adoc[SUSE Observability auf OpenShift installieren]
